[program:openbox]
command=/usr/bin/openbox
environment=DISPLAY=%(ENV_DISPLAY)s
autorestart=true
priority=10

[program:chromium]
command=/usr/bin/chromium
  --no-sandbox
  --window-position=0,0
  --display=%(ENV_DISPLAY)s
  --user-data-dir=/home/neko/.config/chromium
  --no-first-run
  --start-maximized
  --bwsi
  --force-dark-mode
  --disable-file-system
  --disable-gpu
  --disable-software-rasterizer
  --disable-dev-shm-usage
  --user-agent="Mozilla/5.0 (Linux; Android 14; Pixel 8) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Mobile Safari/537.36"
  --touch-events=enabled
  --force-device-scale-factor=3
environment=DISPLAY=%(ENV_DISPLAY)s
autorestart=true
priority=20
