"""Read the Skald sidecar manifest that declares which models this machine
*can* run, independently of whatever is currently loaded in RAM.

The manifest is generated by Skald's ``export_taos_manifest.py`` and written
to ``/etc/taos/skald-models.json`` (configurable via ``TAOS_SKALD_MANIFEST``).
Each entry describes a model the GPU catalog knows about, including the
backend software, port, VRAM requirement, and health URL.

TAOS uses this information to advertise *available* (not-yet-loaded) models
alongside the *loaded* models discovered by live backend probing. The
controller's cluster view then knows what a worker *could* load without
having to consult an external catalog.
"""

from __future__ import annotations

import json
import os
from pathlib import Path
from typing import Any

DEFAULT_MANIFEST_PATH = "/etc/taos/skald-models.json"

# Map Skald software names to TAOS backend types so the worker can
# attach manifest entries to the correct backend dict.
SOFTWARE_TO_BACKEND_TYPE: dict[str, str] = {
    "llamacpp": "llama-cpp",
    "embed": "llama-cpp",
    "kokoro": "kokoro",
    "whisper": "whisper",
}


def load_manifest(path: str | None = None) -> dict[str, Any]:
    """Read the Skald sidecar manifest from disk.

    Args:
        path: Override path.  Falls back to ``TAOS_SKALD_MANIFEST`` env var,
              then ``/etc/taos/skald-models.json``.

    Returns:
        Dict with keys ``resource_id`` (str) and ``models`` (list of dicts).
        Returns an empty manifest when the file is absent (the worker may
        not run alongside Skald).
    """
    manifest_path = Path(path or os.getenv("TAOS_SKALD_MANIFEST", DEFAULT_MANIFEST_PATH))
    if not manifest_path.exists():
        return {"resource_id": "", "models": []}
    return json.loads(manifest_path.read_text())
